[workspace]
description = "A Mojo library for seamlessly mixing compile-time parameters and runtime arguments, enabling flexible optimization strategies and reducing code duplication."
authors = ["gabrieldemarmiesse <gabrieldemarmiesse@gmail.com>"]
channels = ["conda-forge", "https://conda.modular.com/max-nightly", "https://prefix.dev/pixi-build-backends"]
platforms = ["linux-64", "linux-aarch64", "osx-arm64"]
license = "MIT"
license-file = "LICENSE"
readme = "README.md"
homepage = "https://github.com/gabrieldemarmiesse/mojo-parameter-or-arg"
repository = "https://github.com/gabrieldemarmiesse/mojo-parameter-or-arg"
preview = ["pixi-build"]

[tasks]
test = "mojo -I ./src ./tests/test_parameter_or_arg.mojo"
format = "mojo format"

[dependencies]
mojo = ">=25.3.0.dev2025042605"

[package]
name = "mojo-parameter-or-arg"
version = "0.2.0"

[package.build]
backend = { name = "pixi-build-rattler-build", version = "*" }

[feature.util.dependencies]
typer = ">=0.16.0,<0.17"
pyyaml = ">=6.0.2,<7"

[feature.util.tasks]
publish = "python scripts/publish.py build-and-publish"

[environments]
default = { solve-group = "default" }
util = { features = ["util"], solve-group = "default" }

